config/routes.rb
Rails.application.routes.draw do
  get 'pages/secret'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'users#new'

  get 'users/new' => 'users#new', as: :new_user # sign up page with form

  post 'users' => 'users#create'  # create (post) action for when sign up form is submitted:

  get '/login'     => 'sessions#new'   # log in page with form:

  post '/login'    => 'sessions#create'   # create (post) action for when log in form is submitted:

  delete '/logout' => 'sessions#destroy'   # delete action to log out:

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true # checks email address is not blank & that it doesn't already exist in the db

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Make the current_user method available to views also, not just controllers:
  helper_method :current_user

  # Define the current_user method:
  def current_user
    # Look up the current user based on user_id in the session cookie:
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # adding an authorize helper, authroize method redirects user to login page if not logged in:
  def authorize
    redirect_to login_path, alert: 'You must be logged in to access this page.' if current_user.nil?
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # Restrict access so only logged in users can access the secret page:
  before_action :authorize, only: [:secret]

  def secret
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    # No need for anything in here, we are just going to render our
    # new.html.erb AKA the login page
  end

  def create
    # Look up User in db by the email address submitted to the login form and
    # convert to lowercase to match email in db in case they had caps lock on:
    user = User.find_by(email: params[:login][:email].downcase)
    # Verify user exists in db and run has_secure_password's .authenticate()
    # method to see if the password submitted on the login form was correct:
    if user && user.authenticate(params[:login][:password])
      # Save the user.id in that user's session cookie:
session[:user_id] = user.id.to_s
      redirect_to root_path, notice: 'successfully logged in'
    else
      # if email or password incorrect, re-render login page:
      flash.now.alert = "incorrect email or password, try again"
      render :new
    end
end

  def destroy
    # delete the saved user_id key/value from the cookie:
session.delete(:user_id)
    redirect_to login_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
   @user.email.downcase!
    if @user.save
      # If user saves in the db successfully:
      flash[:notice] = "Account created successfully!"
      redirect_to root_path
    else
      # If user fails model validation (eg:bad password or duplicate email)
      flash.now.alert = "Oops, couldn't create account. Please make sure you are using a valid email and password."
      render :new
    end
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    # strong parameters
    params.permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% %>

  <% if current_user %>
    <!-- current_user will return true if a user is logged in -->
    <%= "Logged in as #{current_user.email}" %> | <%= link_to 'Home', root_path %> | <%= link_to 'Log Out', logout_path, method: :delete %>
  <% else %>
    <!-- not logged in -->
    <%= link_to 'Home', root_path %> | <%= link_to 'Log In', login_path %> or <%= link_to 'Sign Up', new_user_path %>
  <% end %>
  <hr>


  <% if notice %>
  <p style="color: green"><%= flash[:notice] %></p>
  <% end %>

  <% if alert %>
    <p style="color: red"><%= flash[:alert] %></p>
  <% end %>

  <% %>
    <%= yield %>
  </body>
</html>

app/views/pages/secret.html.erb
<h1>Secret Page</h1>
<p>This is my secret page! I can only view this if I'm logged in</p>

app/views/users/new.html.erb
<h1>Login Form</h1>
<div>

  <%= form_for @user do |f| %>
    <p>Username: <%= text_field_tag :username %></p>
    <p>Email: <%= text_field_tag :email %></p>
    <p>Password: <%= password_field_tag :password %></p>
    <p>Password_confirmation: <%= password_field_tag :password_confirmation %></p>
    <p><%= submit_tag "Sign up" %>

  <% end %>
</div>